# vim: syntax=dockerfile

FROM ubuntu:noble

LABEL maintainer="Nektar++ Development Team <nektar-users@imperial.ac.uk>"

WORKDIR /root

RUN export DEBIAN_FRONTEND=noninteractive && \
    apt-get update && \
    apt-get install -y \
        packaging-dev cmake git git-buildpackage vim \
        libtbb-dev libfontconfig-dev \
        libboost-iostreams-dev libboost-system-dev libboost-program-options-dev \
        libarpack2-dev \
        libfftw3-dev \
        libhdf5-mpi-dev \
        liblapack-dev \
        libtinyxml-dev \
        mpi-default-dev \
        zlib1g-dev \
        python3-dev python3-numpy python3-pip python3-setuptools \
        libptscotch-dev \
        libocct-data-exchange-dev libocct-modeling-algorithms-dev \
        libocct-foundation-dev libgl-dev \
        libocct-ocaf-dev libocct-visualization-dev \
            libtet1.5-dev libtriangle-dev \
        texlive-base texlive-latex-extra texlive-science \
            texlive-fonts-recommended texlive-pstricks \
            texlive-latex-recommended texlive-pictures \
        doxygen graphviz imagemagick dvipng

RUN groupadd nektar && deluser ubuntu &&  useradd -m -g nektar nektar

# Force update to always run when building image
ARG INVALIDATE_CACHE
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade -y

USER nektar:nektar
WORKDIR /home/nektar
COPY docker/packaging/quiltrc .quiltrc
