# vim: syntax=dockerfile

FROM debian:trixie-slim

LABEL maintainer="Nektar++ Development Team <nektar-users@imperial.ac.uk>"

WORKDIR /root

RUN DEBIAN_RELEASE=trixie && \
    echo "deb http://deb.debian.org/debian ${DEBIAN_RELEASE} non-free" > \
        /etc/apt/sources.list.d/debian-non-free.list && \
    apt-get update && \
    apt-get install -y \
        build-essential debhelper devscripts lintian quilt \
        cmake git git-buildpackage vim \
        libboost-iostreams-dev libboost-system-dev libboost-program-options-dev \
        libarpack2-dev \
        libfftw3-dev \
        libhdf5-mpi-dev \
        liblapack-dev \
        libtinyxml-dev \
        mpi-default-dev \
        zlib1g-dev \
        python3-dev python3-numpy python3-pip python3-setuptools \
        libptscotch-dev libocct-data-exchange-dev \
        libocct-foundation-dev libocct-modeling-algorithms-dev \
        libocct-modeling-data-dev libocct-ocaf-dev libgl-dev \
        libtet1.5-dev libtriangle-dev libtbb-dev libfontconfig-dev\
        texlive-base texlive-latex-extra texlive-science \
            texlive-fonts-recommended texlive-pstricks \
        doxygen graphviz imagemagick dvipng

RUN groupadd nektar && useradd -m -g nektar nektar

# Force update to always run when building image
ARG INVALIDATE_CACHE
RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get dist-upgrade -y

USER nektar:nektar
WORKDIR /home/nektar
COPY docker/packaging/quiltrc .quiltrc
