FROM fedora:40

# Install some basic build requirements.
RUN dnf install -y rpm-build dnf-plugins-core git environment-modules

WORKDIR /root
COPY pkg/redhat/nektar-fedora-40.spec .

# Install build requirements from spec file.
RUN dnf builddep -y nektar-fedora-40.spec && rm -f nektar-fedora-40.spec
